# sorting, searching, counting function

In [1]:
import numpy as np

In [2]:
arr=np.array([31,46,3,51,61,6,1,61,65,165,1,6])

In [3]:
arr

array([ 31,  46,   3,  51,  61,   6,   1,  61,  65, 165,   1,   6])

In [4]:
np.sort(arr)

array([  1,   1,   3,   6,   6,  31,  46,  51,  61,  61,  65, 165])

In [6]:
np.searchsorted(arr,34)

7

In [7]:
arr1=np.array([0,23,654,265,23,533,5,33,5,3,32])

In [8]:
np.count_nonzero(arr1)

10

In [9]:
arr

array([ 31,  46,   3,  51,  61,   6,   1,  61,  65, 165,   1,   6])

In [10]:
np.where(arr>6)

(array([0, 1, 3, 4, 7, 8, 9], dtype=int64),)

In [12]:
np.extract(arr>3, arr)

array([ 31,  46,  51,  61,   6,  61,  65, 165,   6])

In [ ]:
# byte swapping

In [13]:
arr.byteswap()

array([  520093696,   771751936,    50331648,   855638016,  1023410176,
         100663296,    16777216,  1023410176,  1090519040, -1526726656,
          16777216,   100663296])

In [17]:
# copies and views # deep copy and shallow copy

In [15]:
arr

array([ 31,  46,   3,  51,  61,   6,   1,  61,  65, 165,   1,   6])

In [16]:
a=np.copy(arr)

In [19]:
a

array([ 31,  46,   3,  51,  61,   6,   1,  61,  65, 165,   1,   6])

In [20]:
b=arr.view()

In [21]:
b

array([ 31,  46,   3,  51,  61,   6,   1,  61,  65, 165,   1,   6])

In [22]:
arr

array([ 31,  46,   3,  51,  61,   6,   1,  61,  65, 165,   1,   6])

In [23]:
# viws ke case me koi naya data nhi banta nhi jagah par uski ke ander usako refer kar dega

In [ ]:
# matrix library

In [24]:
import numpy.matlib as nm

In [25]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [26]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
# numpy - linear algebra

In [31]:
arr1=np.random.randint([[2,3],[4,5]])

In [30]:
arr2=np.random.randint([[5,3], [2,5]])

In [33]:
np.dot(arr1,arr2)

array([[ 2,  8],
       [ 6, 15]])

In [34]:
arr1@arr2

array([[ 2,  8],
       [ 6, 15]])