In [2]:
import numpy as np

In [ ]:
# isaake liye aap hamesha data pass karoge aaray ya matrix se

In [5]:
l=[1,2,3,4,5,6]
ar=np.array(l)
ar

array([1, 2, 3, 4, 5, 6])

In [3]:
# array ki madad se aap kitane hi dimensional ke  data ko represent kar sakte ho

In [6]:
type(ar) 

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [9]:
a=[2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [ ]:
# en upr ke teeno function ki madad se aap array baan sakte ho

In [12]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4, 5, 6]])

In [13]:
# matrix by default 2D hota h
# and matrix is subset of array 
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5, 6]])

In [14]:
a=np.array(l)

In [15]:
a

array([1, 2, 3, 4, 5, 6])

In [16]:
c=a

In [17]:
c

array([1, 2, 3, 4, 5, 6])

In [19]:
c[0]=10

In [20]:
c

array([10,  2,  3,  4,  5,  6])

In [21]:
a

array([10,  2,  3,  4,  5,  6])

In [22]:
d=np.copy(a)

In [23]:
d

array([10,  2,  3,  4,  5,  6])

In [24]:
a

array([10,  2,  3,  4,  5,  6])

In [25]:
a[1]=100

In [26]:
a

array([ 10, 100,   3,   4,   5,   6])

In [28]:
d

array([10,  2,  3,  4,  5,  6])

# deep copy 
# shallow copy

# ## function to genrate array

In [29]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
iterable=(i*i for i in range(5))

In [33]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [39]:
np.fromstring('234,234', sep=',')

array([234., 234.])

In [40]:
# array data types 

In [49]:
l=([2,3,4,5,6])

In [50]:
ar=np.array(l)

In [52]:
ar.ndim

1

In [53]:
ar2=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [54]:
ar2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [55]:
ar2.ndim

2

In [57]:
ar2.size

10

In [58]:
ar2.shape

(2, 5)

In [59]:
ar.shape

(5,)

In [61]:
ar.dtype

dtype('int32')

In [62]:
ar2.dtype

dtype('int32')

In [63]:
ar22=np.array([(1.4,45,45),(23,45,66)])

In [64]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [65]:
ar22.dtype

dtype('float64')

In [69]:
j=range(5)

In [70]:
list(j)

[0, 1, 2, 3, 4]

In [71]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [72]:
np.arange(2.3,5.6,.2)

array([2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7,
       4.9, 5.1, 5.3, 5.5])

In [73]:
list(np.arange(2.3,5.6,.2))

[2.3,
 2.5,
 2.7,
 2.9000000000000004,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.700000000000001,
 3.9000000000000012,
 4.100000000000001,
 4.300000000000002,
 4.500000000000002,
 4.700000000000002,
 4.900000000000002,
 5.100000000000002,
 5.3000000000000025,
 5.500000000000003]

In [75]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [76]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.zeros((3,4,2)) # 4 row aur 2 column ki 3 matrixx

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [82]:
ar44=np.zeros((8,3,4,2))

In [83]:
ar44

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],

In [84]:
ar44.ndim

4

In [85]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
on=np.ones((2,3,2))

In [88]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [89]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [92]:
np.empty((3,5))

array([[0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        3.496989e-317]])

In [93]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [94]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [95]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [96]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [97]:
 np.random.randn(3,4)

array([[ 1.40841141,  0.8478689 ,  1.37926854, -1.04151966],
       [-1.77369053,  0.64845652, -0.48087347, -0.16314296],
       [ 0.44198519, -0.20952907,  0.02195769,  1.55005343]])

In [98]:
 arr=np.random.randn(3,4)

In [99]:
arr

array([[ 1.60905776, -0.54093945,  0.5443838 , -0.33764154],
       [-2.89151787,  0.82269876, -0.9888035 , -0.57807913],
       [ 0.09927706,  0.21420221,  0.01816639,  0.50243298]])

In [100]:
import pandas as pd

In [101]:
pd.DataFrame(arr)

0         1         2         3
0  1.609058 -0.540939  0.544384 -0.337642
1 -2.891518  0.822699 -0.988803 -0.578079
2  0.099277  0.214202  0.018166  0.502433

In [102]:
np.random.randint(1,110,(3,4))

array([[ 57,  15,  77,  52],
       [ 68, 102,  16,  68],
       [ 86, 108, 109,  93]])

In [103]:
np.random.randint(1,110,(300,400))

array([[ 40,  14,  50, ..., 109,  52,  93],
       [ 54,  10,  90, ...,  94,  75,  54],
       [ 10,  66,  84, ...,  87,  60,  33],
       ...,
       [ 28,  13,   5, ...,  56,  85,  41],
       [ 34,   5,  84, ...,  73,  90,  11],
       [ 88,  13,  50, ..., 102,  38,  57]])

In [105]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("test.csv")

In [106]:
arr=np.random.rand(3,4)

In [107]:
arr

array([[0.21798475, 0.60745919, 0.49142422, 0.39738805],
       [0.71558779, 0.80315865, 0.35164478, 0.85045551],
       [0.83276798, 0.76327962, 0.8472032 , 0.65881915]])

In [108]:
arr.reshape(6,2)

array([[0.21798475, 0.60745919],
       [0.49142422, 0.39738805],
       [0.71558779, 0.80315865],
       [0.35164478, 0.85045551],
       [0.83276798, 0.76327962],
       [0.8472032 , 0.65881915]])

In [110]:
arr.reshape(6,2)

array([[0.21798475, 0.60745919],
       [0.49142422, 0.39738805],
       [0.71558779, 0.80315865],
       [0.35164478, 0.85045551],
       [0.83276798, 0.76327962],
       [0.8472032 , 0.65881915]])

In [111]:
arr.reshape(6,-1)

array([[0.21798475, 0.60745919],
       [0.49142422, 0.39738805],
       [0.71558779, 0.80315865],
       [0.35164478, 0.85045551],
       [0.83276798, 0.76327962],
       [0.8472032 , 0.65881915]])

In [112]:
arr1=arr.reshape(6,-1)

In [113]:
arr1

array([[0.21798475, 0.60745919],
       [0.49142422, 0.39738805],
       [0.71558779, 0.80315865],
       [0.35164478, 0.85045551],
       [0.83276798, 0.76327962],
       [0.8472032 , 0.65881915]])

In [114]:
arr1[1][1]

0.39738804681135775

In [115]:
arr1[2:5,1]

array([0.80315865, 0.85045551, 0.76327962])

In [117]:
arr=np.random.randint(1,100,(5,5))

In [118]:
arr

array([[92, 69, 93, 54, 18],
       [ 9, 25, 58, 52, 49],
       [16, 94, 55,  8, 70],
       [84, 35, 80, 10, 76],
       [ 5, 14, 19, 99,  6]])

In [119]:
arr>50

array([[ True,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [ True, False,  True, False,  True],
       [False, False, False,  True, False]])

In [120]:
arr[arr>50]

array([92, 69, 93, 54, 58, 52, 94, 55, 70, 84, 80, 76, 99])

In [121]:
arr[2:4,[1,2]]

array([[94, 55],
       [35, 80]])

In [122]:
arr[0][0]=5000

In [123]:
arr

array([[5000,   69,   93,   54,   18],
       [   9,   25,   58,   52,   49],
       [  16,   94,   55,    8,   70],
       [  84,   35,   80,   10,   76],
       [   5,   14,   19,   99,    6]])

In [128]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [126]:
arr1

array([[2, 2, 2],
       [1, 2, 2],
       [1, 2, 1]])

In [129]:
arr2

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [130]:
arr1+arr2

array([[4, 2, 2],
       [4, 3, 3],
       [3, 2, 2]])

In [131]:
arr1-arr2

array([[ 0,  0,  0],
       [ 0,  1,  1],
       [-1,  0,  0]])

In [132]:
arr1/arr2

array([[1. , 1. , 1. ],
       [1. , 2. , 2. ],
       [0.5, 1. , 1. ]])

In [134]:
arr1*arr2 # this is not matrixmaultiplication this is simple index multiplication

array([[4, 1, 1],
       [4, 2, 2],
       [2, 1, 1]])

In [136]:
arr1@arr2 # for matrix multiplication

array([[ 8,  4,  4],
       [12,  6,  6],
       [ 6,  3,  3]])

In [137]:
arr1/0

C:\Users\vibha\AppData\Local\Temp\ipykernel_20960\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [138]:
arr1+100

array([[102, 101, 101],
       [102, 102, 102],
       [101, 101, 101]])

In [139]:
arr1**2

array([[4, 1, 1],
       [4, 4, 4],
       [1, 1, 1]])

# broad casting

In [142]:
arr=np.zeros((4,4))

In [141]:
row=np.array([1,2,3,4])

In [144]:
arr+row # ye row wise broadcasting kar raha h 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [145]:
row.T


array([1, 2, 3, 4])

In [147]:
col=np.array([[1,2,3,4]])

In [150]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [151]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [152]:
# broadcasting - ham 1 data le rahe h aur usake baad use bo=roadcast kar rahe h across table

In [153]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
arr1=np.random.randint(1,4,(3,4))

In [157]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.73205081, 1.73205081],
       [1.        , 1.        , 1.73205081, 1.        ],
       [1.41421356, 1.41421356, 1.73205081, 1.73205081]])

In [158]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183, 20.08553692, 20.08553692],
       [ 2.71828183,  2.71828183, 20.08553692,  2.71828183],
       [ 7.3890561 ,  7.3890561 , 20.08553692, 20.08553692]])