In [7]:
# numpy --> array manipulation 

In [10]:
import numpy as np

In [11]:
arr= np.random.randint(1,10, (3,4))

In [12]:
arr

array([[5, 9, 7, 3],
       [8, 9, 1, 5],
       [3, 1, 8, 4]])

In [15]:
arr.reshape(2,313)

ValueError: cannot reshape array of size 12 into shape (2,313)

In [14]:
arr.T

array([[5, 8, 3],
       [9, 9, 1],
       [7, 1, 8],
       [3, 5, 4]])

In [ ]:
arr.flatten()# ye 1 d me convert karta hai data ko

In [17]:
arr1=np.array([1,2,3,4,5,6])

In [18]:
arr1.ndim

1

In [19]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [20]:
np.expand_dims(arr1,axis=0)


array([[1, 2, 3, 4, 5, 6]])

In [21]:
arr

array([[5, 9, 7, 3],
       [8, 9, 1, 5],
       [3, 1, 8, 4]])

In [22]:
np.squeeze(arr)

array([[5, 9, 7, 3],
       [8, 9, 1, 5],
       [3, 1, 8, 4]])

In [23]:
data=np.array([[1], [2],[3]])

In [24]:
data

array([[1],
       [2],
       [3]])

In [25]:
np.squeeze(data)

array([1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 4, 5, 6])

In [27]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [29]:
np.roll(arr1, 2)

array([5, 6, 1, 2, 3, 4])

In [30]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [31]:
# binary operation

In [32]:
arr1=np.random.randint(1,10,(3,4))

In [33]:
arr2=np.random.randint(1,10,(3,4))

In [34]:
arr1

array([[2, 7, 8, 4],
       [6, 9, 9, 5],
       [3, 1, 2, 2]])

In [35]:
arr2

array([[4, 4, 7, 3],
       [1, 1, 8, 3],
       [4, 2, 3, 5]])

In [36]:
arr1+arr2

array([[ 6, 11, 15,  7],
       [ 7, 10, 17,  8],
       [ 7,  3,  5,  7]])

In [37]:
arr1*arr2

array([[ 8, 28, 56, 12],
       [ 6,  9, 72, 15],
       [12,  2,  6, 10]])

In [38]:
arr1/arr2

array([[0.5       , 1.75      , 1.14285714, 1.33333333],
       [6.        , 9.        , 1.125     , 1.66666667],
       [0.75      , 0.5       , 0.66666667, 0.4       ]])

In [39]:
arr1-arr2

array([[-2,  3,  1,  1],
       [ 5,  8,  1,  2],
       [-1, -1, -1, -3]])

In [40]:
arr1%arr2

array([[2, 3, 1, 1],
       [0, 0, 1, 2],
       [3, 1, 2, 2]])

In [41]:
arr1**arr2

array([[      16,     2401,  2097152,       64],
       [       6,        9, 43046721,      125],
       [      81,        1,        8,       32]])

In [42]:
arr1&arr2

array([[0, 4, 0, 0],
       [0, 1, 8, 1],
       [0, 0, 2, 0]])

In [43]:
~arr1

array([[ -3,  -8,  -9,  -5],
       [ -7, -10, -10,  -6],
       [ -4,  -2,  -3,  -3]])

In [44]:
arr1|arr2

array([[ 6,  7, 15,  7],
       [ 7,  9,  9,  7],
       [ 7,  3,  3,  7]])

In [45]:
arr1>arr2

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [46]:
# numpy- string function

In [47]:
arr=np.array(["sudh","kumar"])

In [48]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [50]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [51]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [53]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [54]:
# numpy- mathematical function 

In [55]:
arr1

array([[2, 7, 8, 4],
       [6, 9, 9, 5],
       [3, 1, 2, 2]])

In [56]:
np.sin(arr1)

array([[ 0.90929743,  0.6569866 ,  0.98935825, -0.7568025 ],
       [-0.2794155 ,  0.41211849,  0.41211849, -0.95892427],
       [ 0.14112001,  0.84147098,  0.90929743,  0.90929743]])

In [57]:
np.cos(arr1)

array([[-0.41614684,  0.75390225, -0.14550003, -0.65364362],
       [ 0.96017029, -0.91113026, -0.91113026,  0.28366219],
       [-0.9899925 ,  0.54030231, -0.41614684, -0.41614684]])

In [58]:
np.tan(arr1)

array([[-2.18503986,  0.87144798, -6.79971146,  1.15782128],
       [-0.29100619, -0.45231566, -0.45231566, -3.38051501],
       [-0.14254654,  1.55740772, -2.18503986, -2.18503986]])

In [59]:
np.tanh(arr1)

array([[0.96402758, 0.99999834, 0.99999977, 0.9993293 ],
       [0.99998771, 0.99999997, 0.99999997, 0.9999092 ],
       [0.99505475, 0.76159416, 0.96402758, 0.96402758]])

In [60]:
np.log10(arr1)

array([[0.30103   , 0.84509804, 0.90308999, 0.60205999],
       [0.77815125, 0.95424251, 0.95424251, 0.69897   ],
       [0.47712125, 0.        , 0.30103   , 0.30103   ]])

In [61]:
np.exp(arr1)

array([[7.38905610e+00, 1.09663316e+03, 2.98095799e+03, 5.45981500e+01],
       [4.03428793e+02, 8.10308393e+03, 8.10308393e+03, 1.48413159e+02],
       [2.00855369e+01, 2.71828183e+00, 7.38905610e+00, 7.38905610e+00]])

In [62]:
np.sqrt(arr1)

array([[1.41421356, 2.64575131, 2.82842712, 2.        ],
       [2.44948974, 3.        , 3.        , 2.23606798],
       [1.73205081, 1.        , 1.41421356, 1.41421356]])

In [63]:
np.power(arr1,2)

array([[ 4, 49, 64, 16],
       [36, 81, 81, 25],
       [ 9,  1,  4,  4]], dtype=int32)

In [64]:
np.mean(arr1)

4.833333333333333

In [66]:
np.median(arr1)

4.5

In [67]:
np.var(arr1)

7.8055555555555545

In [69]:
np.min(arr1)

1

In [70]:
np.max(arr1)

9